<!DOCTYPE html>
<html lang="fr-CA">
<head>
    <title>Page principale</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Une ou deux phrases qui décrivent le contenu de la page Web">
    <meta name="author" content="Christiane Lagacé : https://christianelagace.com">
    <link rel="icon" href="favicon.ico">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/mes-styles.css">
    <script src="https://kit.fontawesome.com/b73f095700.js" crossorigin="anonymous"></script>
</head>